// GENERATED by tool/gen_content_fallbacks.py — do not edit by hand.
//
// Compile-time content so Home never renders an empty card, even if
// every bundled asset fails to load. All text is real bundled content.

import 'models/home_data.dart';
import '../state/wotd_provider.dart';

final List<VerseOfTheDay> kFallbackVotdPool = List.unmodifiable([
  VerseOfTheDay(
    'Matthew 11:28',
    'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
    commentarySnippet: 'All are weighed down with burdens that only Christ can remove. The heaviest burden that we bear is the burden of sin. If we were left to bear this burden, it would crush us.',
    author: 'Ellen G. White',
    sourceTitle: 'The Desire of Ages',
  ),
  VerseOfTheDay(
    'Hebrews 12:12',
    'Wherefore lift up the hands which hang down, and the feeble knees;',
    commentarySnippet: 'We are not to become weak-kneed or discouraged because of chastening. We are rather to take heed to our path that the weak be not turned out of the way. We are to watch our influence lest others be led astray, and fail of the grace of God.',
    author: 'M. L. Andreasen',
    sourceTitle: 'The Book of Hebrews',
  ),
  VerseOfTheDay(
    'Romans 8:17',
    'And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.',
    commentarySnippet: 'Who would not be glad if he could be assured that he could have everything he wanted? How many people there are who are filled with unsatisfied longings! This is a world of want and woe.',
    author: 'E.J. Waggoner',
    sourceTitle: 'Waggoner on Romans',
  ),
  VerseOfTheDay(
    'Romans 8:23',
    'And not only they, but ourselves also, which have the firstfruits of the Spirit, even we ourselves groan within ourselves, waiting for the adoption, to wit, the redemption of our body.',
    commentarySnippet: 'The preceding lessons have shown us that the possession of the Holy Spirit marks our relation to God as sons. It is the pledge of the life and inheritance to come.',
    author: 'E.J. Waggoner',
    sourceTitle: 'Waggoner on Romans',
  ),
  ]);

final List<WordOfTheDay> kFallbackWotdPool = List.unmodifiable([
  WordOfTheDay('Faith', 'Faith is in general the persuasion of the mind that a certain statement is true (Phil. 1:27; 2 Thess. 2:13). Its primary idea is trust. A thing is tru...', normalized: 'faith'),
  WordOfTheDay('Mercy', 'Compassion for the miserable. Its object is misery. By the atoning sacrifice of Christ a way is open for the exercise of mercy towards the sons of men...', normalized: 'mercy'),
  WordOfTheDay('Hope', 'One of the three main elements of Christian character (1 Cor. 13:13). It is joined to faith and love, and is opposed to seeing or possessing (Rom. 8:2...', normalized: 'hope'),
  WordOfTheDay('Covenant', 'A contract or agreement between two parties. In the Old Testament the Hebrew word berith is always thus translated. Berith is derived from a root whic...', normalized: 'covenant'),
  WordOfTheDay('Redemption', 'The purchase back of something that had been lost, by the payment of a ransom. The Greek word so rendered is apolutrosis, a word occurring nine times ...', normalized: 'redemption'),
  WordOfTheDay('Charity', '(1 Cor. 13), the rendering in the Authorized Version of the word which properly denotes love, and is frequently so rendered (always so in the Revised ...', normalized: 'charity'),
  ]);
