#!/usr/bin/env python3
"""Regenerates lib/data/content_fallbacks.dart from the bundled assets.

The generated constants are the last line of defence against blank Home
cards: real KJV verse text + real commentary excerpts (VOTD) and real
dictionary entries (WOTD), compiled into the binary so they exist even if
every asset fails to load.

Run from the repo root after changing bible.db or commentary.json:
    python3 tool/gen_content_fallbacks.py
"""
import json
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / 'assets/bible/bible.db'
COMMENTARY = ROOT / 'assets/commentary/commentary.json'
BOOKS = ROOT / 'lib/data/bible_books.dart'
OUT = ROOT / 'lib/data/content_fallbacks.dart'

# (reference, commentary source) pairs chosen for clean, self-contained
# excerpts. The script fails loudly if any of them disappears.
VOTD_PICKS = [
    ('Matthew', 11, 28, 'All are weighed down'),
    ('Hebrews', 12, 12, 'We are not to become weak-kneed'),
    ('Romans', 8, 17, 'Who would not be glad'),
    ('Romans', 8, 23, 'The preceding lessons'),
]
WOTD_PICKS = ['faith', 'mercy', 'hope', 'covenant', 'redemption', 'charity']


def snippet(text):
    # Mirrors _extractSnippet in lib/state/home_provider.dart.
    sentences = [s.strip() for s in re.findall(r'[^.!?]+[.!?]', text)]
    return ' '.join(sentences[:3]) if sentences else text.strip()


def clean_verse(text):
    # Mirrors cleanVerseForDisplay in lib/state/home_provider.dart.
    for ch in ('\u00b6', '\u2039', '\u203a', '[', ']'):
        text = text.replace(ch, '')
    return re.sub(r'\s+', ' ', text).strip()


def dart_str(s):
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
    s = s.replace('\n', ' ').replace('\r', ' ')
    return "'" + s + "'"


def main():
    with DB.open('rb') as f:
        if f.read(16) != b'SQLite format 3\x00':
            sys.exit(f'{DB} is not a SQLite file (Git LFS pointer?). '
                     'Run: git lfs install && git lfs pull')
    names = BOOKS.read_text().split("'")[1::2][:66]
    book_no = {n.lower(): i + 1 for i, n in enumerate(names)}
    entries = json.loads(COMMENTARY.read_text())['entries']
    con = sqlite3.connect(f'file:{DB}?mode=ro', uri=True)

    votd = []
    for book, ch, v, prefix in VOTD_PICKS:
        row = con.execute(
            "SELECT text FROM verses WHERE translation_id='kjv' AND "
            'book_number=? AND chapter=? AND verse=?',
            (book_no[book.lower()], ch, v)).fetchone()
        if not row:
            sys.exit(f'Missing KJV verse {book} {ch}:{v}')
        verse_text = clean_verse(row[0])
        match = None
        for e in entries:
            s = e.get('scope', {})
            if (s.get('type') == 'verse' and s.get('book') == book
                    and str(s.get('chapter')) == str(ch)
                    and str(s.get('verse')) == str(v)
                    and e.get('text', '').lstrip().startswith(prefix)):
                match = e
                break
        if not match:
            sys.exit(f'Missing commentary for {book} {ch}:{v} ({prefix}...)')
        votd.append((f'{book} {ch}:{v}', verse_text, snippet(match['text']),
                     match.get('author', 'Unknown'), match.get('source', '')))

    wotd = []
    for w in WOTD_PICKS:
        row = con.execute(
            'SELECT display_headword, definition FROM dictionary '
            'WHERE normalized_word=? ORDER BY source LIMIT 1', (w,)).fetchone()
        if not row:
            sys.exit(f'Missing dictionary entry: {w}')
        d = row[1].replace('\n', ' ')
        wotd.append((row[0], d[:150] + '...' if len(d) > 150 else d, w))

    lines = [
        '// GENERATED by tool/gen_content_fallbacks.py — do not edit by hand.',
        '//',
        '// Compile-time content so Home never renders an empty card, even if',
        '// every bundled asset fails to load. All text is real bundled content.',
        '',
        "import 'models/home_data.dart';",
        "import '../state/wotd_provider.dart';",
        '',
        'final List<VerseOfTheDay> kFallbackVotdPool = List.unmodifiable([',
    ]
    for ref, text, snip, author, source in votd:
        lines += [
            '  VerseOfTheDay(',
            f'    {dart_str(ref)},',
            f'    {dart_str(text)},',
            f'    commentarySnippet: {dart_str(snip)},',
            f'    author: {dart_str(author)},',
            f'    sourceTitle: {dart_str(source)},',
            '  ),',
        ]
    lines += ['  ]);', '', 'final List<WordOfTheDay> kFallbackWotdPool = List.unmodifiable([']
    for word, snip, norm in wotd:
        lines.append(f'  WordOfTheDay({dart_str(word)}, {dart_str(snip)}, '
                     f'normalized: {dart_str(norm)}),')
    lines += ['  ]);', '']
    OUT.write_text('\n'.join(lines))
    print(f'Wrote {OUT.relative_to(ROOT)}: {len(votd)} VOTD, {len(wotd)} WOTD')


if __name__ == '__main__':
    main()
